[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && node server.cjs"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
NODE_ENV = "production" 